CREATE TABLE AUDIT_LOGS
(
    AUDIT_ID          VARCHAR2(64) PRIMARY KEY,
    OCCURRED_AT_UTC   TIMESTAMP NOT NULL,
    USER_ID           VARCHAR2(50),
    USER_NAME         VARCHAR2(250),
    SESSION_ID        VARCHAR2(64),
    CORRELATION_ID    VARCHAR2(100),
    HTTP_METHOD       VARCHAR2(20),
    PATH              VARCHAR2(1000),
    CONTROLLER_NAME   VARCHAR2(250),
    ACTION_NAME       VARCHAR2(250),
    AUDIT_ACTION      VARCHAR2(250),
    STATUS_CODE       NUMBER(10),
    SUCCEEDED         NUMBER(1) NOT NULL,
    DURATION_MS       NUMBER(19) NOT NULL,
    IP_ADDRESS        VARCHAR2(100),
    USER_AGENT        VARCHAR2(1000),
    REQUEST_SUMMARY   CLOB,
    RESPONSE_SUMMARY  CLOB,
    ERROR_MESSAGE     CLOB
);

CREATE INDEX IX_AUDIT_LOGS_OCCURRED_AT
ON AUDIT_LOGS (OCCURRED_AT_UTC);

CREATE INDEX IX_AUDIT_LOGS_USER_ID
ON AUDIT_LOGS (USER_ID);

CREATE INDEX IX_AUDIT_LOGS_SESSION_ID
ON AUDIT_LOGS (SESSION_ID);

CREATE INDEX IX_AUDIT_LOGS_CORRELATION_ID
ON AUDIT_LOGS (CORRELATION_ID);

CREATE INDEX IX_AUDIT_LOGS_ACTION
ON AUDIT_LOGS (AUDIT_ACTION);