CREATE TABLE AUTH_SESSIONS
(
    SESSION_ID       VARCHAR2(64) PRIMARY KEY,
    USER_ID          VARCHAR2(50) NOT NULL,
    USER_NAME        VARCHAR2(250),
    CREATED_AT_UTC   TIMESTAMP NOT NULL,
    EXPIRES_AT_UTC   TIMESTAMP NOT NULL,
    REVOKED_AT_UTC   TIMESTAMP,
    IP_ADDRESS       VARCHAR2(100),
    USER_AGENT       VARCHAR2(1000)
);

CREATE TABLE AUTH_REFRESH_TOKENS
(
    REFRESH_TOKEN_ID       VARCHAR2(64) PRIMARY KEY,
    SESSION_ID             VARCHAR2(64) NOT NULL,
    USER_ID                VARCHAR2(50) NOT NULL,
    TOKEN_HASH             VARCHAR2(500) NOT NULL,
    CREATED_AT_UTC         TIMESTAMP NOT NULL,
    EXPIRES_AT_UTC         TIMESTAMP NOT NULL,
    USED_AT_UTC            TIMESTAMP,
    REVOKED_AT_UTC         TIMESTAMP,
    REPLACED_BY_TOKEN_HASH VARCHAR2(500),
    CREATED_BY_IP          VARCHAR2(100),
    USER_AGENT             VARCHAR2(1000),

    CONSTRAINT FK_AUTH_REFRESH_SESSION
        FOREIGN KEY (SESSION_ID)
        REFERENCES AUTH_SESSIONS (SESSION_ID),

    CONSTRAINT UQ_AUTH_REFRESH_TOKEN_HASH
        UNIQUE (TOKEN_HASH)
);

CREATE INDEX IX_AUTH_REFRESH_TOKENS_SESSION
ON AUTH_REFRESH_TOKENS (SESSION_ID);

CREATE INDEX IX_AUTH_REFRESH_TOKENS_USER
ON AUTH_REFRESH_TOKENS (USER_ID);

CREATE INDEX IX_AUTH_SESSIONS_USER
ON AUTH_SESSIONS (USER_ID);